Hyperparameter checks
wpilibsuite/Axon pull request #207
Opened 2021-06-09 18:44 UTC by technoAl

2021-06-09 19:49 UTC, GrantPerkins requested changes
Can still train with no dataset selected.

2021-06-10 15:32 UTC, AustinShalit commented on packages/client/src/components/project/input/Buttons.tsx
> +    (parameters.data?.project?.percentEval || 0) <= 0
We use this multiple times. Can we extract to a function?

2021-06-10 15:33 UTC, AustinShalit commented on packages/client/src/components/project/input/Buttons.tsx
> +    return <Button> Invalid Parameters </Button>;
Be sure to set the styling of these buttons to be disabled so users don't try to click them.

2021-06-10 15:33 UTC, AustinShalit commented on packages/client/src/components/project/input/Buttons.tsx
> +    return <Button> Requires Dataset </Button>;
Be sure to set the styling of these buttons to be disabled so users don't try to click them.

2021-06-10 15:34 UTC, AustinShalit reviewed
Small feedback.

2021-06-10 15:51 UTC, GrantPerkins approved these changes
Works on my machine :)

2021-06-12 04:53 UTC, merged