Reset volume button in settings
wpilibsuite/Axon pull request #216
Opened 2021-06-17 18:39 UTC by GrantPerkins

2021-06-17 18:47 UTC, GrantPerkins commented
Resolves #139

2021-06-20 05:24 UTC, AustinShalit requested changes

2021-06-20 05:24 UTC, AustinShalit commented on packages/client/src/index.tsx
> +// Learn more docs service workers: https://bit.ly/CRA-PWA
Revert

2021-06-20 05:24 UTC, AustinShalit commented on packages/client/src/serviceWorker.ts
> +// To learn more docs the benefits of this project and instructions on how to
Revert

2021-06-20 05:24 UTC, AustinShalit commented on packages/launcher/src/index.tsx
> +// Learn more docs service workers: https://bit.ly/CRA-PWA
Revert

2021-06-20 05:24 UTC, AustinShalit commented on packages/launcher/src/serviceWorker.ts
> +// To learn more docs the benefits of this project and instructions on how to
Revert

2021-06-20 05:24 UTC, AustinShalit commented on packages/server/src/resolvers/Mutation.ts
> +      (await dataSources.projectService.reset())
Do these need to have sequentially or can they happen in parallel?

2021-06-21 13:56 UTC, GrantPerkins commented on packages/server/src/resolvers/Mutation.ts
> +      (await dataSources.projectService.reset())
Now in parallel.

2021-06-22 01:04 UTC, AustinShalit requested changes

2021-06-22 01:04 UTC, AustinShalit commented on packages/server/src/resolvers/Mutation.ts
> +      dataSources.projectService.reset()
I think you can use
```suggestion
      sequelize.sync({ force: true })
```
https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#instance-method-sync

to really reset the entire thing without leaving anything behind.

2021-06-23 15:35 UTC, AustinShalit commented
Also, we should add a button/menu bar item in the launcher that'll really try to reset everything by calling docker delete.

2021-06-29 14:16 UTC, GrantPerkins commented
![image](https://user-images.githubusercontent.com/24625614/123813609-0dff7580-d8c3-11eb-8e1a-1959180df1af.png)

2021-06-29 15:09 UTC, AustinShalit approved these changes

2021-06-29 15:10 UTC, AustinShalit requested changes

2021-06-29 15:10 UTC, AustinShalit commented on packages/server/src/resolvers/Mutation.ts
> +  resetVolume: async (parent, args, { docker, dataSources }) => {
See automated review on this line: https://github.com/wpilibsuite/Axon/pull/216/checks?check_run_id=2943497452

2021-06-30 00:41 UTC, AustinShalit approved these changes

2021-06-30 00:42 UTC, merged