Updating README
wpilibsuite/Axon pull request #95
Opened 2021-01-11 17:52 UTC by phonymacoroni

Update README to reflect new instructions

2021-01-11 18:31 UTC, GrantPerkins requested changes

2021-01-11 18:31 UTC, GrantPerkins commented on README.md
> +- "raise the floor, don't lower the ceiling". We try to enable teams with limited programming knowledge and/or mentor
This shouldn't be a bullet.

2021-01-11 22:17 UTC, phonymacoroni commented on README.md
> +- "raise the floor, don't lower the ceiling". We try to enable teams with limited programming knowledge and/or mentor
resolved

2021-01-12 02:30 UTC, GrantPerkins approved these changes

2021-01-12 02:31 UTC, merged